services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-demo
    volumes:
      - ./logs:/logs
      - ./config:/config
      - ./data:/data
      - ./plugins:/plugins
      - ./init.cypher:/var/lib/neo4j/init.cypher
      - ./init-neo4j.sh:/usr/local/bin/init-neo4j.sh # Mount the startup script
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc"] # Add this line to install APOC
    # Overwrite the command to run our custom startup script
    command: ["/bin/bash", "/usr/local/bin/init-neo4j.sh"]
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
