[pytest]
DJANGO_SETTINGS_MODULE = CIS.settings
pythonpath = app
# Limit discovery to the Django app tests
testpaths = app/eccr/tests
# Show extra summary info on failures
addopts = -ra

# You can uncomment to fail fast while iterating
# addopts = -ra -x
