# Generated by Django 5.2.4 on 2025-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoDomain',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
            ],
        ),
    ]
