# Generated by Django 5.2.8 on 2025-12-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0002_djangodomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldss_host', models.CharField(help_text='Enter the host url for the LDSS (Schema Service) to use.', max_length=200)),
            ],
        ),
    ]
